version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    versioning-strategy: increase
    schedule:
      interval: "weekly"
      day: "sunday"
    commit-message:
      prefix: chore
      include: scope
    groups:
      dependencies:
        patterns:
          - "*"
